styled-components/styled-components-website

components/CaptureScroll.js, components/LiveEdit.js, components/Navbar/Sidebar.js
=> Add scroll capturing to LiveEditor and Sidebar

components/api/typescript.js, components/basics/extending-styles.js, components/basics/styling-any-components.js
These are all I could find, good job!
The new intro copy is very good ❤️
=> docs: fix copy issues

components/homepage-getting-started.js, pages/index.js
=> Add them badges

pages/index.js
=> Better homepage example

components/basics/react-native.js
This PR updates RN examples & add migration informations for v1 users.
See https://github.com/styled-components/styled-components/issues/835 for context.
=> Migration informations for RN users

components/advanced/server-side-rendering.js
https://github.com/styled-components/styled-components/issues/453#issuecomment-298502900 Updated the docs
=> Fixed StyleSheetManager doesn't get the sheet.instance

LICENSE, package.json, yarn.lock
=> Add license, Chore(package): update next to 2.4.0

components/faqs/support-for-css-frameworks.js, pages/_document.js, pages/docs.json, pages/docs/faqs.js
PR request in related with the issue #49
=> Add section about CSS frameworks

components/DocsLayout.js, components/SeoHead.js, pages/_document.js, pages/docs/advanced.js, pages/docs/api.js, pages/docs/basics.js, pages/docs/faqs.js, pages/docs/index.js, pages/docs/tooling.js, pages/index.js, test/components/__snapshots__/DocsLayout.spec.js.snap
Added dynamic description fields as well as other fields like canonical.
=> Should Now improve SEO #82

sections/basics/styling-any-components.js
Just added a little clarification there - it's very easy to miss in the docs. 
My team and I stumbled on this subject for couple of days.
By the way - awesome library! :trophy:
=> Clarify className usage on styled(Component)

sections/api/helpers/index.js
Helper doesn't render correctly
=> Fix api/helpers page

package.json, pages/docs.json, pages/docs/tooling.js, sections/tooling/styled-theming.js, yarn.lock
=> Add styled-theming

pages/_document.js
=> Implement Google Analytics

components/Code.js, test/components/__snapshots__/Code.spec.js.snap, test/pages/__snapshots__/index.spec.js.snap, test/sections/__snapshots__/homepage-getting-started.spec.js.snap
#130 
Based upon Github `inline code` style.
=> Update inline-code style

sections/tooling/stylelint.js
Also fixed a few stray NOTE's (as I noticed that the markdown renderer automatically adds these)
=> Added Stylelint note about --fix option

sections/advanced/refs.js
=> Update docs ref example so as to not promote bad practices

sections/advanced/server-side-rendering.js
Update the docs for server-side-rendering with Next.js and add reference to an example from the Next.js repo.
=> Update configuration for SSR with Next.js

sections/advanced/security.js
There's more to do here, but this is a good start. Reference issue: #102
=> Link to CSS.escape from security section

.eslintrc, sections/basics/motivation.js
Fixed an issue with a broken layout of the motivation video.
1. Go to https://www.styled-components.com/docs/basics#motivation
2. Switch to a mobile device in dev tools
=> Fix video aspect ratio

pages/index.js, test/pages/__snapshots__/index.spec.js.snap
=> Add ZEIT Now shoutout

sections/basics/extending-styles.js
Fixes a broken link I found while reading the docs 😄
=> Fix link to Comp.extend vs. styled(Comp) FAQ

package.json, sections/homepage-getting-started.js, server.js, test/pages/__snapshots__/index.spec.js.snap, test/sections/__snapshots__/homepage-getting-started.spec.js.snap, yarn.lock
=> feat: add image proxy for img shield badges 

sections/api/helpers/css.js
Not the biggest issue, but it was bothering me :)
Thank you very much, everyone.
=> Add space before colon

sections/faqs/reverse-selectors.js
=> Added note on nested components and the distinction between RC and SC

sections/advanced/server-side-rendering.js
https://www.styled-components.com/docs/advanced#server-side-rendering
=> fix: bad encoding of style tag

pages/docs.json, pages/docs/faqs.js, sections/faqs/override-styles-with-higher-specificity.js
Closes #187 cc @mxstbr I simply took your explanation from https://github.com/styled-components/styled-components/issues/1253#issuecomment-337871693 and adjusted it a bit.
=> Higher specificity faq

pages/docs.json, pages/docs/faqs.js, sections/faqs/when-to-use-attrs.js
As suggested on [Twitter](https://twitter.com/mxstbr/status/950289161227030528)
=> Add a section to FAQs on when to use attrs

sections/tooling/stylelint.js
Adding a known issue to the Stylelint Processor as discussed in https://github.com/styled-components/stylelint-processor-styled-components/issues/130
@chinesedfan do you agree that this is the correct message to display?
=> Add Known Issues section to docs/tooling/stylelint

sections/basics/alternative-installation.js
https://mathiasbynens.be/notes/html5-levels#type-attributes
=> Omit <script type>

sections/advanced/server-side-rendering.js
to be merged after https://github.com/styled-components/styled-components/pull/1430
=> streaming rendering docs

sections/tooling/stylelint.js
Issues are no longer present https://github.com/styled-components/stylelint-processor-styled-components/pull/143
=> Remove known issues section that is no longer relevant

sections/tooling/stylelint.js
I will be merging in https://github.com/styled-components/stylelint-processor-styled-components/pull/167 any second now and publishing it, and the addition should be self explanatory as to why it is added
=> Add note on using stylelint v9+

sections/tooling/stylelint.js
From:
- https://github.com/styled-components/stylelint-processor-styled-components/pull/172
- https://github.com/styled-components/stylelint-processor-styled-components/pull/171
=> Port over stylelint-processor-styled-components doc changes

sections/advanced/server-side-rendering.js
in 3.2.0 release styled-components automatically does streaming SSR rehydration now.
=> removed info about consolidateStreamedStyles()

pages/docs.json, pages/docs/faqs.js, sections/faqs/html-attribute-warnings.js
=> Add FAQ documentation for HTML attribute warnings

sections/advanced/existing-css.js
=> Fix typo in advanced section of docs

.travis.yml, pages/index.js
=> add @probablyup to core contributors footer

components/Anchor.js, components/Link.js, components/Nav/MobileNavbar.js, pages/_document.js, sections/basics/motivation.js, test/components/NavBar/__snapshots__/MobileNavbar.spec.js.snap, test/components/NavBar/__snapshots__/NavLinks.spec.js.snap, test/components/NavBar/__snapshots__/Navbar.spec.js.snap, test/components/NavBar/__snapshots__/SidebarMenus.spec.js.snap, test/components/NavBar/__snapshots__/index.spec.js.snap, test/components/__snapshots__/Anchor.spec.js.snap, test/components/__snapshots__/DocsLayout.spec.js.snap, test/components/__snapshots__/Link.spec.js.snap, test/components/__snapshots__/NextPage.spec.js.snap
I used Lighthouse to identify and address some accessibility issues. It does not address the following issues:
- Background and foreground colors do not have a sufficient contrast ratio.
- [id] attributes on the page are not unique
I plan on opening an Issue around ```[id] attributes on the page are not unique```
=> Accessibility

sections/api/typescript.js
Okay, I believe this should work now :)
https://github.com/styled-components/styled-components-website/pull/252#issuecomment-405678860
=> fix escaping on Typescript docs

components/CaptureScroll.js, components/LiveEdit.js, next.config.js, package.json, pages/index.js, server.js, test/components/NavBar/__snapshots__/Logo.spec.js.snap, test/components/NavBar/__snapshots__/MobileNavbar.spec.js.snap, test/components/NavBar/__snapshots__/NavButton.spec.js.snap, test/components/NavBar/__snapshots__/NavLinks.spec.js.snap, test/components/NavBar/__snapshots__/NavSeparator.spec.js.snap, test/components/NavBar/__snapshots__/Navbar.spec.js.snap, test/components/NavBar/__snapshots__/Search.spec.js.snap, test/components/NavBar/__snapshots__/Sidebar.spec.js.snap, test/components/NavBar/__snapshots__/SidebarMenus.spec.js.snap, test/components/NavBar/__snapshots__/Text.spec.js.snap, test/components/NavBar/__snapshots__/index.spec.js.snap, test/components/__snapshots__/Anchor.spec.js.snap, test/components/__snapshots__/Code.spec.js.snap, test/components/__snapshots__/DocsLayout.spec.js.snap, test/components/__snapshots__/Label.spec.js.snap, test/components/__snapshots__/Layout.spec.js.snap, test/components/__snapshots__/Link.spec.js.snap, test/components/__snapshots__/LiveEdit.spec.js.snap, test/components/__snapshots__/NextPage.spec.js.snap, test/components/__snapshots__/Note.spec.js.snap, test/components/__snapshots__/Table.spec.js.snap, yarn.lock
This broke the site at runtime.
=> Revert "upgrade to beta.0"

pages/docs.json
=> remove unused anchor from faq section

components/Nav/SidebarMenus.js, test/components/NavBar/__snapshots__/index.spec.js.snap, test/components/__snapshots__/DocsLayout.spec.js.snap
window is undefined, so the docs sidebar would always render collapsed on the server but expanded on the client.
=> Fix docs sidebar menu SSR issue

sections/basics/installation.md
The docs were using an outdated set of npm flags
=> Update `npm i --save-dev` instruction

sections/faqs/library-authors.md
=> [FAQs] - Suggests using rollup-plugin-peer-deps-external with rollup

pages/docs.json, pages/docs/faqs.md, sections/faqs/create-react-app.md
@mxstbr let me know if there's any other useful info you'd recommend adding
=> add FAQ section on create-react-app

pages/docs.json, pages/docs/advanced.md, sections/advanced/style-objects.md
As the last bit under the advanced section
=> Document style object usage

sections/tooling/stylelint.md
I took the issue (https://github.com/styled-components/styled-components-website/issues/334)
and fixed it.
=> Fix bad json formatting (issue #334)

sections/tooling/stylelint.md
=> Fix bad formatting

components/Anchor.js, test/components/__snapshots__/Anchor.spec.js.snap
It's a bit friendlier on mobile and less complicated CSS.
=> move the hover link to after the headline text

sections/basics/getting-started.md, sections/basics/installation.md, sections/homepage/getting-started.md
..and clean up the getting started and installation sections in the
basics docs a little bit
=> Remove references to v4 beta

sections/tooling/babel-macro.md
=> fix cosmiconfig link

sections/tooling/babel-plugin.md
+ Include extra minification/transpiling info from the babel plugin repo
In relation with https://github.com/styled-components/babel-plugin-styled-components/issues/146
=> Update babel-plugin documentation

sections/homepage/components.js, sections/homepage/getting-started.md
pr aims to especially improve mobile positioning of the example buttons shown on the homepage. pr also ships some ships some semicolon fixes inserted by prettier (?).
=> optimize example button positioning on homepage

sections/api/primary/css-prop.md, sections/api/primary/index.md
Don't merge until styled-components/babel-plugin-styled-components#172 is released!
=> Add the css prop to the API documentation

pages/docs.json, pages/docs/faqs.md, sections/faqs/declare-components-in-render-method.md
Closes https://github.com/styled-components/styled-components-website/issues/75
* Add `Why should i avoid to declare styled components in the render method?` to FAQ section.
=> FAQ: Why should i avoid to declare styled components in the render method?

sections/api/typescript.md
Quite simple PR, but I think this link explains all is needed:
https://spectrum.chat/styled-components/help/typescript-support-for-props~c501855f-8bc6-4f0a-a84a-417ccb90a27e
=> Update typescript.md (its outdated)

pages/index.js
Adds a logo slider similar to nextjs slider as requested in #400
=> Added logo slider similar to nextjs

sections/advanced/theming.md
Closes #407.
Let me know what you think @mxstbr.
PS: Prettier updated lines 100/104/109 automatically.
=> 📖🎨👶🏼 ThemeProvider single child documentation

sections/api/helpers/create-global-style.md
The order really matters.
Spent 1h trying to solve this issue that was a matter of just ordering the component to the top.
Hope these changes helps someone.
=> Update GlobalStyle position in app example

sections/basics/attaching-additional-props.md
Updates the docs on adding additional props to include the new syntax 🙌 
Closes: #418
=> Update .attr docs

sections/tooling/babel-plugin.md
=> Typo fix for Tooling -> Better Debugging section

sections/api/typescript.md
See https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e7a5287d64170226de85838477564b786cb0ff2a/types/react/index.d.ts#L452-L458
=> docs(typescript): stateless -> function components

sections/faqs/declare-components-in-render-method.md
=> Fix grammar: Change "i" to "I"

sections/api/helpers/create-global-style.md
=> add web-only tag to createGlobalStyle api head

pages/docs.json
missing piece of https://github.com/styled-components/styled-components-website/pull/443
=> Fix typo "styling any component"

sections/basics/extending-styles.md
Fix typo in the Extending Styles example
<buton...
<Button...
=> hotfix: Fix typo on the button usage

sections/tooling/babel-plugin.md
I noticed this errant "adds" when reading the docs this afternoon. Thanks!
=> Fix type on babel-plugin.md

components/UsersLogos/index.js
=> corrected the issue in which the slider was not showing all the logos

components/UsersLogos/index.js
Related issue #536 
Please review and merge :)
=> Fixed infinte slider slutter issue

sections/tooling/stylelint.md
Just because something is obvious to you, that does not mean it will be obvious to everyone.
=> No need to abuse your readers

sections/basics/react-native.md
=> Update note on flex shorthands for react native

sections/advanced/theming.md
https://github.com/styled-components/styled-components/pull/2706
=> Get rid of the ThemeProvider single child context restriction

companies-manifest.js
Adds some additional information about the company and project in the manifest
=> ➕ company name, project repo where applicable

components/Slider/ShowcaseBody.js, components/Slider/ShowcaseLink.js, pages/showcase.js
Closes #615 
It also comes with a couple of other smaller tweaks to the page.
=> Showcase tweaks

companies-manifest.js
I corrected the Fortnite Master title from 'Fornite Master' to 'Fortnite Master'.
=> Corrected the Fortnite Master title

sections/tooling/babel-plugin.md, test/components/__snapshots__/DocsLayout.spec.js.snap
=> Add namespace documentation

sections/advanced/theming.md
(fixes #716) 
Changed "Overidden" to "Overridden" in theming.md
=> Changed "Overidden" to "Overridden" (fixes #716)

sections/basics/attaching-additional-props.md
clarify how multiple layers of .attrs work to prevent confusions like in this issue: https://github.com/styled-components/styled-components/issues/3178
=> clarify how multiple layers of .attrs work

README.md, pages/docs.json, pages/docs/faqs.md, sections/api/typescript.md, sections/faqs/missing-native-import.md
Re the upcoming changes in  https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49914
I'll probably merge ^ today, so ideally this could go through pretty soon
=> Doc updates for upcoming DT changes

sections/api/typescript.md
Fix: https://github.com/styled-components/styled-components-website/issues/762
=> Fix sentence on typescript.md section

sections/homepage/getting-started.md
@probablyup might need your assistance here, how do i generate one of those `<Badge>` tags? or is what I've added fine?
I've removed the spectrum link as it doesn't make sense to keep directing people there.
=> adding badge for Discord fixes #764

components/BlmBanner.js
Fix #773
before in issue
after fix
=> fix bimbanner on mobile

sections/basics/extending-styles.md
changeing "/" to "#" so to we do not get redirected to homepage if we click the button given in the example
=> changed href="/" to href="#"

pages/showcase.js
Just adding a head to Showcase page 😇
=> Add showcase head

pages/docs.json, pages/docs/tooling.mdx, sections/tooling/swc-plugin.mdx, test/components/NavBar/__snapshots__/SidebarMenus.spec.tsx.snap, test/components/NavBar/__snapshots__/index.spec.tsx.snap, test/components/__snapshots__/DocsLayout.spec.tsx.snap
**This pull request makes the following changes:**
* Fixes issue : #907 
**Checklist:**
Ping @quantizor
=> Added Doc For SWC #907

components/DocsLayout.tsx, components/VisuallyHidden.tsx, test/__mocks__/@styled-icons/material.js, test/components/__snapshots__/DocsLayout.spec.tsx.snap, utils/githubApi.ts
This PR adds in an RSS icon and feed link. I've also added a visually hidden component for screen readers.
Closes https://github.com/styled-components/styled-components-website/issues/598
(Apologies for the massive screenshot 😅)
=> RSS Feed for Releases page

sections/basics/installation.mdx
Hi, I added a link for an explanation about "resolutions".
This update would make it easier to understand what "resolutions" is, as it is not obvious to those who are not familiar with yarn or npm.
=> Add link for an explanation about "resolutions"
