components/advanced/server-side-rendering.js
I just upgraded the SSR API to the latest RC. I couldn't figure out how to get the generated CSS into the `<head>` when using `ReactDOM.renderToStaticMarkup()` and was about to try PR'ing this exact same method. Would be good to document it somewhere 😁
=> Add `sheet.getStyleElement()` to the demo

components/Navbar/Sidebar.js
`position: fixed` causes the sidebar to get repainted on the CPU with every scroll event, small hack to delegate this to the GPU.
=> reduce repaints on fixed sidebar

components/CaptureScroll.js, components/Navbar/index.js, pages/_document.js
Hey @philpl—I've had a look at the issue, and you're right, it does appear to be the way you're managing scrolling.
I've added a couple of fixes, but keen to get your feedback on whether there's a more "styled-components" way of doing it. Especially when attaching classes to the body.
- Added a sticky class to the body when the navigation is expanded, which adds `overflow: hidden;`
- Added event listeners when loading on the desktop breakpoint, to trigger when resizing between desktop and mobile. This shouldn't impact mobile.
Happy to discuss.
=> #10 Resolved the scroll issue when changing breakpoints

pages/index.js
Before they would be the first thing that would hit your eye, which is
suboptimal as we've got a great tagline AND a live editor
Fixed that by making them `opacity: 0.6`, but I'm open to other
solutions. Making them white would be kinda awesome maybe? Any clues how
to do that?
=> Slightly fade out the logos on the homepage

components/api/primary/styled.js
Input sizes are [numbers](https://www.w3schools.com/tags/att_input_size.asp), I'm not sure if that was the intention but changing a pixel value makes it a little confusing.
=> drop pixels from input size

components/basics/attaching-additional-props.js
Fix type attribute typo under "Adding additional props"
=> fix typo under "Adding additional props" section

components/basics/styling-any-components.js
(ref https://github.com/styled-components/styled-components/issues/858)
I added a note to use `style` instead of `className` for `react-native`.
=> Add react-native note in styling-any-components

pages/_document.js, static/manifest.json
Use a theme color that goes well with the header.
Before & after:
=> Theme color that goes with the header

components/advanced/server-side-rendering.js
Just replaced `css` for `styleTags`, because `sheet.getStyleElement()` is really returning style tags, not plain css.
=> fix: more consistent example

components/api/flow.js
flow-typed is an example of a package that'd rarely be used so it might be a good idea to run it through `npx` for those with npm versions that support it
=> Add option to run flow-typed with npx

components/advanced/babel-plugin.js, pages/docs.json, pages/docs/advanced.js, test/components/NavBar/__snapshots__/Menu.spec.js.snap, test/components/NavBar/__snapshots__/index.spec.js.snap, test/components/__snapshots__/DocsLayout.spec.js.snap
Closes #13 and creates a section in advanced with the babel plugin docs
=> Babel plugin

components/faqs/support-for-css-frameworks.js
🔥 🚒 
Looks like the current `faq` page is 500-ing. Ran into this while working on #52.
Happily it's a quick fix, just missing a `Link` import.
=> Add missing Link import

components/advanced/babel-plugin.js
Using just "styled-components" can cause a hard-to-understand error
("Cannot create styled-component for component: [object Object]") if
the plugin hasn't actually been installed, since Babel tries to load
the styled-components module itself instead of the plugin. Fully
qualifying the plugin name ensures that a sensible error is thrown
if the plugin isn't present.
=> Use fully qualified plugin name in Babel config

components/advanced/babel-plugin.js
Latest version of the babel plugin does not prefix the component name anymore.
=> Remove `sc` prefix

sections/homepage-getting-started.js, test/sections/__snapshots__/homepage-getting-started.spec.js.snap
just a step-by-step clarification that `{ css }` must be imported in order to perform interpolation.
before:
> The last step is that we need to define what a primary button looks like. To do that we interpolate a function into our template literal, which gets passed the props of our component:
```
const Button = styled.button`
border-radius: 3px;
padding: 0.25em 1em;
margin: 0 1em;
background: transparent;
color: palevioletred;
border: 2px solid palevioletred;
${props => props.primary && css`
background: palevioletred;
color: white;
`}
`;
```
after:
> The last step is that we need to define what a primary button looks like. To do that we also import { css } from styled-components and interpolate a function into our template literal, which gets passed the props of our component:
```
import …
```
=> update info on interpolation at homepage

sections/tooling/stylelint.js
Adds documentation about the new `moduleName` option of the stylelint processor.
**DO NOT MERGE UNTIL https://github.com/styled-components/stylelint-processor-styled-components/pull/112 IS MERGED!**
/cc @emilgoldsmith @ismay
=> Add documentation about moduleName option

components/md.js
As discussed in #123 I added a type check for the `strings` variable
=> fix: support calling md as a normal function too

pages/_document.js
My previous Google Analytics implementation wasn't working, only firing
on first visit. Google Tag Manager has the power to listen to history
changes and fire analytics events when they happen, so I've configured
Google Tag manager to do exactly that.
This means our analytics setup is now working perfectly and tracking
pageviews as it should.
=> Integrate Google tag manager

pages/_document.js
Loading Operator Mono in the `<head>` meant we were blocking the first render by quite a long time. The font had to be completely loaded before the browser could construct the CSSOM, meaning until then nothing was happening making our perceived loading time a lot slower than it needed to be.
By moving the fonts `.css` file at the bottom of the `<body>` we have a first render before that font is loaded, making perceived performance a lot faster.
This does give us a FOUT (flash of unstyled text), BUT since it's only the font we use for code it's unnoticable and/or very small.
PageSpeed Insights before:
PageSpeed Insights after:
Check out the FOUT on your own machine by going to this deploy: https://styled-components-docs-qldaglwxhk.now.sh
=> Unblock first render by moving font link

sections/basics/attaching-additional-props.js
"or pass a prop third-party prop" --> "or pass a third-party prop"
Trying out styled-components and reading through the docs, just noticed this.
=> Fix type in Attaching Additional Props

components/Code.js, sections/advanced/theming.js, test/components/__snapshots__/Code.spec.js.snap, test/pages/__snapshots__/index.spec.js.snap, test/sections/__snapshots__/homepage-getting-started.spec.js.snap
Here's my attempt at https://github.com/styled-components/styled-components-website/issues/116.
I thought a bit about whether to add this info as part of the main theming section (the first one) or as a separate one and went for a separate one in the end, to keep the explanations from growing too much.
Did you have anything else in mind on where to put this?
Also, I didn't actually mention anything about the prop being reserved. Should I?
PS. You'll notice I changed the `line-height` of the code blocks - that's to keep the text in `monospace` font aligned with everything else in titles and content text. 
Looking forward to feedback & further instructions :) Thanks!
=> Docs for the `theme` prop

utils/elementToText.js, utils/titleToDash.js
Fix #105
The following bugs were fixed:
- titleToDash would not remove all non-alphanumeric characters
- titleToDash would not take multiple whitespaces into account
- elementToText would not take trailing and leading whitespaces into
account
- elementToText would not normalise subsequent, multiple whitespaces
This should improve the behaviour of all slugification
=> Fix elementToText and titleToDash (slugifiers)

test/utils/elementToText.spec.js, utils/elementToText.js
Sidebar was linking to https://www.styled-components.com/docs/advanced#server-side-rendering but the anchor in the doc itself rendered as https://www.styled-components.com/docs/advanced#server-side-rendering- (an extra dash at the end).
This was due to the heading having the tag ` | v2` appended, the string was being split on the pipe but the extra spaces weren't being trimmed.
=> Fix sidebar links by trimming output of elementToText

sections/advanced/server-side-rendering.js
Next.js section now looks like this:
Let me know if you need any changes 😃
=> Remove Next.js section's inline snippet and fix typo

sections/basics/react-native.js
This relates to #6. I don't know if it really solves this issue, but reading the discussion it seemed like a good tradeoff between keeping the design and adding a playground element.
Hope this helps, if you need any changes just ping me 👍 
(Embedding doesn't work due to https://github.com/rexxars/commonmark-react-renderer/issues/9 by the way)
=> Add link to snack demo

pages/docs.json, utils/elementToText.js
The "[When should I use `styled()?`](https://www.styled-components.com/docs/faqs#when-should-i-use-styled)" link under FAQs was not in the right order compared to the other headings on the page. Its anchor was also broken. 
This fixes that link's order and anchor, along with any other slugs generated from titles that had `code` markdown.
The slugs were fine on dev but broken in the build. It was because Preact uses x.children compared to x.props.children in React.
=> Fix slug generation and sidebar order

pages/docs.json, pages/docs/faqs.js, sections/faqs/override-inline-styles.js, sections/faqs/override-styles-with-higher-specificity.js
This builds on #199 and adds another section about overriding inline styles.
In the section I describe using the CSS style `element-attr` with `!important` since it seems to be the recommended way to override inline styles. In all honesty, I am having a hard time seeing how it differs from simply using `!important`. It might be more backwards compatible, but I cannot verify this.
So, we can either leave this as is, since it's sure to work, or we can simplify it to only use `!important`.
Sources
* https://css-tricks.com/override-inline-styles-with-css/
* https://stackoverflow.com/questions/16813220/how-can-i-override-inline-styles-with-external-css
* https://www.sitepoint.com/override-inline-css/
=> Override inline styles

components/Anchor.js, components/Layout.js, components/md.js, pages/releases.js
A second pass at fixing #202 (per @philpl's suggestions in #213). This includes the `TertiaryHeading` component for `h4`'s (anything greater than `## Heading 2` was just rendering h3) from the closed #213.
Also adds ability to specify an id prefix when `md()` is used as a normal function. This is being used to keep from having a bunch of duplicate anchors/ids on the releases page. Closes #214.
for your viewing/checking for functionality/regressions: https://styled-components-docs-ntjcjteypa.now.sh/
=> Normalize headings on releases page

sections/basics/extending-styles.js
This change fixes a broken link to the FAQ page
=> Fix broken link: when to use styled

sections/advanced/server-side-rendering.js
This clarifies that it's not possible to use tags from `sheet.getStyleTags()`  in the same tree as the component that `sheet` is wrapping. For example, one could mistakenly try to do something like this to include their app and the generated `<style>` tags as part of a larger component, but in fact this does not work:
```js
const wrapperConstructor = () => {
const stylesheet = new ServerStyleSheet();
const wrappedComponent = stylesheet.collectStyles(<YourApp />);
return (
<div>
{stylesheet.getStyleElement()}
{wrappedComponent}
</div>
);
};
```
=> Clarify that SSR methods only work after wrapped components are rendered

sections/faqs/library-authors.js
A follow-up to the discussion that started in https://github.com/styled-components/styled-components/issues/1076#issuecomment-362336469
This is an attempt to expand FAQ section for library authors, explaining why exactly they would need to move `styled-components` in their `package.json` to `peer` and `dev` dependencies and how to properly exclude module with different bundling tools
Deployed a preview: https://styled-components-docs-wpotnoywqn.now.sh/docs/faqs#i-am-a-library-author-should-i-bundle-styledcomponents-with-my-library
/cc: @mxstbr
=> Expand FAQ for library authors

sections/tooling/styled-theming.js
It seems like there is a typo in the style-components tooling section;
The first parameter for `theme.variants` is the 'theme'-mode and not the prop name used chose the variant. 
https://github.com/styled-components/styled-theming#themevariantsname-prop-themes
=> Fix typo in tooling section

sections/api/primary/styled-component.js
I've been reading the documentation and I found a broken link reference.
When you click on `see Tagged Template Literal`, we're redirect to an unknown route and consequently get 404. ([Direct Link to the oficial doc](https://www.styled-components.com/docs/api#styledcomponent))
Just add "doc" prefix and now it's working as should be.
=> Fix link reference

sections/tooling/babel-plugin.js
Fixes the broken `tagged-template-literals` url in the [_Template String Transpilation_](https://www.styled-components.com/docs/tooling#template-string-transpilation) section.
=> Fix broken tagged-template-literals URL

sections/tooling/test-utilities.js
Hey,
while browsing the *Tooling* section all CLI examples start off with `npm install`, except for the *Test Utilities* section where it's still a `yarn add` reference. Since many people will just copy the commands, this is inconsistent, and add unwanted files (`yarn-lock`). :)
=> Use consistent CLI examples in Tooling section

sections/basics/coming-from-css.md
In a comparison between CSSModules and Styled Components, the Styled Components example was missing the onClick methods to actually modify state.
Relates to issue #311
=> Adds button onClick to styled-component example

sections/api/old/inner-ref.md
since we're using v4 for the website, the code can't run properly
closes #320
=> switch innerRef example to simple syntax highlighting

sections/advanced/components-as-selectors.md
Add `flex: none` to the svg icon to prevent it from shrinking to oblivion in the [referring to other components example](https://www.styled-components.com/docs/advanced#referring-to-other-components).
**Before**:
**After**:
=> Add flex:none to an SVG in examples

sections/basics/animations.md
Per https://github.com/styled-components/styled-components/issues/2024, keyframes don't work on `react-native`, but this is currently not noted anywhere in the documentation.
=> Add note that keyframes don't work on react-native

sections/basics/coming-from-css.md
Just a simple orthographic fix.
=> Correct spelling for pseudo(elements|selectors) in documentation

sections/faqs/migration-v4.md
1. v4 typings are now out
2. react-router* upgrade no longer needed
=> update v4 migration guide

sections/advanced/refs.md
Hi! 👋
I'm not sure if there is a fix for this issue already in another branch or something, but I noticed that the example located at https://www.styled-components.com/docs/advanced#refs doesn't currently work and throws this error:
This PR attempts to fix that example.
This issue could have been fixed by removing `.base`, which I'm not sure why it was used for.
```diff
<Input
ref={this.setInputRef}
placeholder="Hover to focus!"
-   onMouseEnter={() => this.input.base.focus()}
+   onMouseEnter={() => this.input.focus()}
/>
```
However, the example uses a callback-style Ref. I figured it could be updated to use the new `createRef` API as well, unless there is reason not to.
**Before**
https://www.styled-components.com/docs/advanced#refs
**After** …
=> Update (fix) docs Refs example

sections/basics/animations.md
Because of the discussion with Max and me at spectrum (https://spectrum.chat/thread/29aa3ecf-0927-40d6-963f-c475a389298e) I created that PR.
I added a code snippet which consists the animation value in a css helper.
I am not sure if my description for the need of the css helper is correct and moreover I am not sure if keyframes returns a unique keyframe object or something else.
=> Add css helper in animations example

sections/faqs/browser-support.md
Quick type change.
This actually caused a bit of confusion when deciding whether or not to use this tool.
=> Updated grammar to make this a little clearer

sections/tooling/babel-macro.md
- Make explicit that you should also import named imports from the macro.
- Add a section to enforce imports from the macro.
=> Improve Babel Macro documentation.

sections/faqs/migration-v4.md
Looks like both `js` and `jsx` work. But they have slightly different syntax highlighting.
=> fix syntax highlighting

sections/api/primary/styled-component.md, sections/basics/extending-styles.md
Closes https://github.com/styled-components/styled-components-website/issues/371
* Add a note to the **Extending Styles** section referencing and discouring the usage of the previous API's : `.withComponent` and `.extend`.
* Remove the reference to **Extending Styles** from the `.withComponent` section.
=> Add previous API's note to extending styles section

components/LiveEdit.js, test/components/__snapshots__/LiveEdit.spec.js.snap
Closes https://github.com/styled-components/styled-components-website/issues/395
Not really sure what's the reason that caused the visual bug in the code editor on chrome 70, but adding a relative position to the `editorMixin` in `LiveEdit.js` fixes the scrollbar issue without changing the behaviour of anything else.
=> Code editor scroll bar bug on chrome 70

sections/api/primary/css-prop.md
Do not merge this before https://github.com/styled-components/babel-plugin-styled-components/pull/181 and https://github.com/styled-components/styled-components/pull/2244 are shipped!
=> Add note about Babel macro support for css prop

sections/faqs/duplicated-styled-components.md
After fighting with lerna for 2 days, I think I found a way to use styled-components in a library package and import that package in my main application without warnings about duplicate imports.
I've added 2 examples of how to hoist styled-components (automatically and manually) to the documentation.
=> Add example of how hoisting can help in a monorepo

sections/advanced/server-side-rendering.md
Just like the Next.js section of the server-side rendering docs.
Short but useful for Gatsby + styled-components users!
(tested locally)
=> Add docs for server-side rendering on Gatsby

pages/index.js
So far I've implemented basic functionality requested in #439 but without the api request logic i mentioned in #439 (so far no feedback from SimilarWeb on my request for an api key). So did this searching/typing thingy to implement and test the feature organization taking in consideration an eventually upcoming SimilarWeb api implementation. But, data is valid, the component works as it should as far as I see and thus could be used for deployment if you want.
Some notes on the implementation:
- considering handling the global rank data receipt via api, I had to replace the React Fragment implementation with javascript array. Reason: a Fragment doesn't list its children (which would be all the logos), but using the api I'd need the children (logos) in order do to a proper element cloning …
=> sorted logos using SimilarWeb global rank as sorting indicator

sections/advanced/theming.md
Adds a sentence and small code example of getting theme outside of styled components when using React Hooks. Right now there is an example using ```withTheme``` for HOCs, but I think this would be a good addition for anyone using Hooks in their codebase to save a little time searching for the way to achieve this in Hooks.
**Before**
**After**
=> Add Hooks example to Themeing > Getting theme without styled components

components/Nav/NavButton.js, test/components/NavBar/__snapshots__/MobileNavbar.spec.js.snap, test/components/NavBar/__snapshots__/NavButton.spec.js.snap, test/components/NavBar/__snapshots__/Navbar.spec.js.snap, test/components/NavBar/__snapshots__/index.spec.js.snap, test/components/__snapshots__/DocsLayout.spec.js.snap
Currently, this results in the following CSS:
```css
.c1 + { padding-left: 0; }
```
Why? `NavBar` is undefined at the time of usage, newer versions of Babel error for this.
After this change:
```css
.c2 + .c1 { padding-left: 0; }
```
=> Fix NavButton CSS

sections/tooling/stylelint.md
It looks like the setup instructions for stylelint are partly a copy from the processor's readme, that's why I also files a similar PR there: https://github.com/styled-components/stylelint-processor-styled-components/pull/286 .
In this PR I additionally to the processor repo.
=> Tooling Stylelint: improve setup instructions

sections/faqs/migration-v5.md
Clarifies the note that the `attrs` object-form removal in v5 was only for the subfunction support, not the object-form itself, which is still supported.
=> docs: clarify v5 attrs object-form deprecation

sections/basics/react-native.md
Pre-Change: URL was Broken
Post-Change: URL now directs to correct source.
=> Update react-native.md Broken URL

sections/basics/installation.md
Hello,
In your docs here https://styled-components.com/docs/basics#installation in the CDN part, you mention the `<script>` tag to add:
```html
<script src="https://unpkg.com/styled-components/dist/styled-components.min.js"></script>
```
You also mention to put it after the React CDN bundles with a [link](https://reactjs.org/docs/cdn-links.html) to them.
Since last version of styled components, there is a new (production-) dependency on `react-is` pacakge.
So doing this:
```html
<script crossorigin src="https://unpkg.com/react@16/umd/react.production.min.js"></script>
<script crossorigin src="https://unpkg.com/react-dom@16/umd/react-dom.production.min.js"></script>
<script crossorigin src="https://unpkg.com/styled-components/dist/styled-components.min.js"></script>
```
Results in the …
=> Add react-is dependency for CDN installation

pages/index.js
Hi! I noticed the text in the "Discover more" button wasn't centered and I couldn't resist to center it.
Before:
After:
=> Vertically center "Discover more" text 

components/Footer/index.js, sections/advanced/server-side-rendering.md
[ZEIT is now Vercel](https://vercel.com/blog/zeit-is-now-vercel) so we can update the footer:
Also replaces `github.com/zeit/next.js` with `github.com/vercel/next.js` in two links.
=> Rename ZEIT Now to Vercel

components/UsersLogos/index.js
Add the ability to disable the brands animations on the website if the user has set the device to reduce or remove animations system-wide.
From [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion): _Readers with vestibular motion disorders may wish to enable the reduce motion feature on their device before viewing the animation._
This PR fixes the issue [#3278](https://github.com/styled-components/styled-components/issues/3278) from the **styled-components** repository.
The reduce motion can be enabled on macOS by going to **System Preferences > Accessibility > Display** and turning **Reduce motion** _on_.
=> Feature: remove brands animation on the website if 'prefers-reduced-motion' is on

sections/advanced/tagged-template-literals.md
I just discovered that in the process of flattening CSS, styled-components [ignores](https://github.com/styled-components/styled-components/blob/08390f25fa7e353107f0a30080075104cec6426f/packages/styled-components/src/utils/flatten.js#L13-L16) interpolations that evaluate to `undefined`, `null`, `false`, or an empty string. I think this fact may not be widely known, though, because in a certain [component library](https://github.com/Faithlife/styled-ui) I'm working on, I'm seeing a lot of `${props.condition ? 'rule-name: value;' : ''}` in styled components instead of `${props.condition && 'rule-name: value;'}`, seemingly out of a fear that `false` or `undefined` will stringify and break their CSS.
So I've written a short addition to the Tagged Template Literals section that lets people …
=> Add a note about using short-circuit evaluation to conditionally add CSS rules

sections/api/typescript.md
If this isn't done then the types won't be found, if `types` is already set.  Per author @Methuselah96: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49914#issuecomment-779531774
=> RN: Add instruction for setting types in tsconfig

README.md
[learnnextjs.com](https://learnnextjs.com/) 404s now instead of redirecting.
=> Update Next.js links in readme

sections/tooling/styled-theming.md
Fixed a couple of syntax errors in font-family strings, as well as a bit of formatting regarding self-closing JSX elements.
=> Fix syntax and formatting in styled-theming.md

sections/tooling/jest.md
The snapshot example contained color: green; even though the example code contains color: red;
=> Fix snapshot example

sections/tooling/babel-plugin.md
This PR adds documentation for the `meaninglessFileNames` option recently introduced in the babel plugin in styled-components/babel-plugin-styled-components#304.
=> Document the babel plugin meaninglessFileNames option

sections/advanced/server-side-rendering.md
Hi!
With the new Next.js update, we don't need babel with a custom document for the styles to work, so I've updated the examples references.
English is not my first language, so feedback is also appreciated. Thanks!
=> feat: update nextjs integration docs and examples

sections/basics/animations.md
Context: "Keyframes are lazily injected when they're used, which is how they can be code-splitted, so you have to use the `css` helper for shared style fragments"
=> Change 'code-splitted' to 'code-split'

sections/faqs/duplicated-styled-components.md
Update documentation to remove deprecated command:
> Filtering by arguments is deprecated. Please use the pattern option instead.
[styled-components docs](https://styled-components.com/docs/faqs#duplicated-module-in-node_modules)
[yarn docs](https://classic.yarnpkg.com/lang/en/docs/cli/list/#toc-yarn-list-depth-pattern)
=> yarn list - filtering by arguments is deprecated

sections/faqs/html-attribute-warnings.md
Prefer simpler transient props, instead of destructuring for HTML warning.
=> Upgrade FAQ to use transient props to resolve HTML warning

sections/advanced/server-side-rendering.md
I just fixed an issue in a project I recently started working on where the getInitialProps configuration was missing, so this change is just to clarify the need for this configuration.
=> Improving explanation about how to add styled-components with SSR in a Next.js project

sections/api/typescript.md
typings should not be included in production dependencies
=> fix: remove typings from production dependencies

sections/api/typescript.md
I've got stuck trying to type my theme props passed by ThemeProvider, then I found myself i've extending DefaultTheme from styled-components module, not for styled-components/native one. I think this little change can speed up other developers to setup the provider.
=> docs: Add new react native declarations file

components/CodeBlock.js, package.json, pages/index.js, yarn.lock
There is no change since `rc.2`, but I changed the example in home page, so we can only edit the style, previously if we remove some code, the render part will be shown, which I think is not intended, as I can see if we don't edit the code, the render part is not editable, so I changed to simply hide it from editing, correct me if I'm wrong on that
=> update react-runner to v1.0

components/Layout.js, test/components/__snapshots__/DocsLayout.spec.js.snap, test/components/__snapshots__/Layout.spec.js.snap
Currently, the layout on mobile is able to be overflowed quite a lot (see below). I found a change from PR #743 that seemed to be related to the layout breaking. 
Just a small change,
Hope this helps!
Kyle
=> Add back max-width:100% to Layout__Content styled component to fix broken mobile docs layout

sections/api/typescript.md
Remove some confusion around the code snippets for setting up the theme interface with React-Native:
- Add missing import for the declaration merging example
- ~~Replace the `ThemeInterface` import with the `DefaultTheme` that was augmented in the previous step. The `ThemeInterface` and the `theme.ts` file from which it is imported are never mentioned before this step.~~
- Remove unnecessary code snippet
=> clarify typescript documentation examples for react-native

sections/basics/attaching-additional-props.mdx
Fixed visual syntax error that failed to show the correct inputs for the docs/basics#attaching-additional-props page.
This is what the page looks live:
There is now no syntax error, and the desired input fields are displayed on the page:
=> fixed visual syntax error for basics#attaching-additional-props

sections/api/primary/styled-component.mdx
this fixes a compilation error in the example. the generic parameter must be set on the `attrs` function so its parameter's function parameter gets the correct type and props are accessible without type error.
=> fixed example for styled components 6 types

sections/faqs/migration-v6.mdx
In v5, prop forwarding behaved differently depending on if the target was an HTML element, or a React Component.  
This PR updates the code example showing how to re-implement the default behavior that existed in v5 in a way that more closely matches the v5 behavior.
=> Update v6 migration guide for shouldForwardProp

components/Slider/Navigation.tsx, components/UsersLogos/index.tsx
- On the Showcase page, users were unable to access the left and right slider navigators for displaying the previous and next company showcases. These navigators rely on left and right arrow keys for interaction.
- I've added HTML attributes that allow users to tab to these sections of the page, and I've provided clear instructions for navigation. Although these elements are buttons, the instruction "use left/right arrow to navigate" should suffice for users with impairments.
Here is the change visualized. Changes were made in Slider/Navigation.tsx. 
https://github.com/styled-components/styled-components-website/assets/51212933/6d662adf-97f2-4585-9f5b-453c46a47b56
- This issue suggested allowing users to 'pause' scrolling animated content in compliance with [WCAG 2.1 Criterion 2.2.2: …
=> Improved accessibility in Slider/Navigation.tsx and UserLogos/index.tsx

package.json, sections/api/primary/css-prop.mdx, sections/faqs/create-react-app.mdx, sections/tooling/babel-macro.mdx, test/components/NavBar/__snapshots__/Navbar.spec.tsx.snap, test/components/NavBar/__snapshots__/index.spec.tsx.snap, test/components/__snapshots__/DocsLayout.spec.tsx.snap, test/components/__snapshots__/Note.spec.tsx.snap, yarn.lock
[More info](https://github.com/styled-components/styled-components/issues/4064)
=> chore: retire macro docs

components/Link.tsx, components/Nav/Social.tsx, test/components/Link.spec.tsx, test/components/NavBar/__snapshots__/Navbar.spec.tsx.snap, test/components/NavBar/__snapshots__/index.spec.tsx.snap, test/components/__snapshots__/DocsLayout.spec.tsx.snap, test/components/__snapshots__/Link.spec.tsx.snap
This pull request updates the `Link` component and enables accepting the `target` prop in order to enable opening of the links in a new tab. Updated tests and snapshots. Updated **GitHub** and **Medium** links, they are now being opened in a new tab.
🍀
=> Updated `Link` Component

sections/api/primary/css-prop.mdx
This PR updates the `css-prop` API reference's [Usage with TypeScript section](https://styled-components.com/docs/api#usage-with-typescript) to inform readers using higher versions than `styled components` v6 that they can simply import the `CssProp` type from the `styled-component` package rather than installing a separate types package from [Definitely Typed](https://github.com/DefinitelyTyped/DefinitelyTyped).
Here is the updated version of the CSS Prop section: https://styled-components-ns1cyl5l8-styledcomponents.vercel.app/docs/api#usage-with-typescript
=> docs: update the css-prop installation guide for users using v6
